name: Rust

on: [push]

jobs:
  windows_build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: make_artifacts_folder
      run: mkdir artifacts

    - name: Build_no_color
      run: cargo build --release --features no_color
    - name: copy_artifacts
      run: copy target\release\happy_server.exe artifacts\hs_no_color.exe

    - name: Build_english
      run: cargo build --release --features english
    - name: copy_artifacts
      run: copy target\release\happy_server.exe artifacts\hs_english.exe

    - name: Build_english_no_color
      run: cargo build --release --features english --features no_color
    - name: copy_artifacts
      run: copy target\release\happy_server.exe artifacts\hs_english_no_color.exe

    - name: Build_defalut
      run: cargo build --release
    - name: copy_artifacts
      run: copy target\release\happy_server.exe artifacts\happy_server.exe

    - uses: actions/upload-artifact@v1 
      with:
        name: Windows
        path: artifacts/



  ubunutu_build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: make_artifacts_folder
      run: mkdir artifacts

    - name: Build_no_color
      run: cargo build --release --features no_color
    - name: copy_artifacts
      run: cp target/release/happy_server artifacts/hs_no_color

    - name: Build_english
      run: cargo build --release --features english
    - name: copy_artifacts
      run: cp target/release/happy_server artifacts/hs_english

    - name: Build_english_no_color
      run: cargo build --release --features english --features no_color
    - name: copy_artifacts
      run: cp target/release/happy_server artifacts/hs_english_no_color

    - name: Build_defalut
      run: cargo build --release
    - name: copy_artifacts
      run: cp target/release/happy_server artifacts/happy_server

    - uses: actions/upload-artifact@v1 
      with:
        name: Ubuntu 20.04
        path: artifacts/



  mac10_build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: make_artifacts_folder
      run: mkdir artifacts

    - name: Build_no_color
      run: cargo build --release --features no_color
    - name: copy_artifacts
      run: cp target/release/happy_server artifacts/hs_no_color

    - name: Build_english
      run: cargo build --release --features english
    - name: copy_artifacts
      run: cp target/release/happy_server artifacts/hs_english

    - name: Build_english_no_color
      run: cargo build --release --features english --features no_color
    - name: copy_artifacts
      run: cp target/release/happy_server artifacts/hs_english_no_color

    - name: Build_defalut
      run: cargo build --release
    - name: copy_artifacts
      run: cp target/release/happy_server artifacts/happy_server

    - name: Build_defalut
      run: cargo build --release
    - name: copy_artifacts
      run: copy target/release/happy_server artifacts/happy_server

    - uses: actions/upload-artifact@v1 
      with:
        name: macOS Catalina 10.15
        path: artifacts/



  mac_big_build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: make_artifacts_folder
      run: mkdir artifacts

    - name: Build_no_color
      run: cargo build --release --features no_color
    - name: copy_artifacts
      run: cp target/release/happy_server artifacts/hs_no_color

    - name: Build_english
      run: cargo build --release --features english
    - name: copy_artifacts
      run: cp target/release/happy_server artifacts/hs_english

    - name: Build_english_no_color
      run: cargo build --release --features english --features no_color
    - name: copy_artifacts
      run: cp target/release/happy_server artifacts/hs_english_no_color

    - name: Build_defalut
      run: cargo build --release
    - name: copy_artifacts
      run: cp target/release/happy_server artifacts/happy_server

    - uses: actions/upload-artifact@v1 
      with:
        name: macOS Big Sur 11
        path: artifacts/