name: Rust

on: [push]

jobs:
  ubunutu_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build_no_color
      run: cargo build --release --features no_color
    - name: Build_english
      run: cargo build --release --features no_color
    - name: Build_english_no_color
      run: cargo build --release --features english --features no_color
    - name: Build_defalut
      run: cargo build --release
    - uses: actions/upload-artifact@v1 
      with:
        name: happy_server
        path: target/release/happy_server

  windows_build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: make_artifacts_folder
      run: mkdir artifacts
      
    - name: Build_no_color
      run: cargo build --release --features no_color
    - name: copy_artifacts
      run: copy target\release\happy_server.exe artifacts\hs_no_color.exe

    - name: Build_english
      run: cargo build --release --features english
    - name: copy_artifacts
      run: copy target\release\happy_server.exe artifacts\hs_english.exe

    - name: Build_english_no_color
      run: cargo build --release --features english --features no_color
    - name: copy_artifacts
      run: copy target\release\happy_server.exe artifacts\hs_english_no_color.exe

    - name: Build_defalut
      run: cargo build --release

    - uses: actions/upload-artifact@v1 
      with:
        name: windows
        path: artifacts/